# Pre-commit hooks for code quality and consistency
# Run: pre-commit install
# Manual run: pre-commit run --all-files

default_language_version:
  python: python3.12
  node: 20.11.0

repos:
  # ==========================================
  # General hooks for all files
  # ==========================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-case-conflict

  # ==========================================
  # Python/Django Backend Hooks
  # ==========================================

  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.12
        args: [--config=backend/pyproject.toml]
        files: ^backend/.*\.py$

  # isort - Python import sorter
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--settings-path=backend/pyproject.toml]
        files: ^backend/.*\.py$

  # Ruff - Python linter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: [--config=backend/pyproject.toml, --fix]
        files: ^backend/.*\.py$

  # djLint - Django template linter
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.1
    hooks:
      - id: djlint-django
        files: ^backend/.*\.html$
        args: [--configuration=backend/pyproject.toml]

  # MyPy - Python type checker (optional, can be slow)
  # Uncomment if you want strict type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.2
  #   hooks:
  #     - id: mypy
  #       args: [--config-file=backend/pyproject.toml]
  #       files: ^backend/.*\.py$
  #       additional_dependencies: [django-stubs, djangorestframework-stubs]

  # ==========================================
  # JavaScript/TypeScript Frontend Hooks
  # ==========================================

  # ESLint - JavaScript/TypeScript linter
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.15.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.(js|jsx|ts|tsx|vue)$
        args: [--fix, --config=frontend/.eslintrc.cjs]
        additional_dependencies:
          - eslint@9.15.0
          - '@typescript-eslint/parser@8.16.0'
          - '@typescript-eslint/eslint-plugin@8.16.0'
          - eslint-plugin-vue@9.31.0
          - eslint-config-prettier@9.1.0
          - eslint-plugin-prettier@5.2.1

  # Prettier - JavaScript/TypeScript/Vue formatter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|jsx|ts|tsx|vue|css|scss|json|md)$
        args: [--config=frontend/.prettierrc.json, --write]

  # ==========================================
  # Security Checks
  # ==========================================

  # Bandit - Python security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [-r, backend/, -f, json, --skip, B101]
        files: ^backend/.*\.py$

  # Safety - Check Python dependencies for vulnerabilities
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.3.3
  #   hooks:
  #     - id: python-safety-dependencies-check
  #       files: ^backend/requirements.*\.txt$

  # ==========================================
  # Documentation & Markdown
  # ==========================================

  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: [--fix]
        files: \.md$

# Configuration for pre-commit ci service (if using)
ci:
  autofix_prs: true
  autofix_commit_msg: '[pre-commit.ci] auto fixes from pre-commit hooks'
  autoupdate_schedule: weekly
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
