# Generated by Django 5.1.3 on 2025-09-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="s3_version_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
