# Generated by Django 5.1.3 on 2025-09-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_s3_version_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="is_expanded",
            field=models.BooleanField(default=False),
        ),
    ]
